apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: serdarpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: serdarpipelinesjavascriptdocker 
    spec:
      containers:
        - name: serdarpipelinesjavascriptdocker 
          image: mycontainerregistry66.azurecr.io/serdarpipelinesjavascriptdocker
          ports:
          - containerPort: 8080